/*
商城系统商品表ddl
*/

CREATE DATABASE /*!32312 IF NOT EXISTS*/`mall` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `mall`;

########## 商品表 ##########

/* 品牌表 */
DROP TABLE IF EXISTS `goods_brand`;
CREATE TABLE `goods_brand` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '品牌名称',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='品牌表';

/* 分类表 */
DROP TABLE IF EXISTS `goods_category`;
CREATE TABLE `goods_category` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='分类表';

/* 增值保障 */
DROP TABLE IF EXISTS `goods_safeguard`;
CREATE TABLE `goods_safeguard` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '保障名称',
  `price` DECIMAL(9,2) NOT NULL COMMENT '保障价格',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='增值保障';

/* sku表 */
DROP TABLE IF EXISTS `goods_sku`;
CREATE TABLE `goods_sku` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(50) NOT NULL COMMENT 'sku编号,唯一',
  `name` VARCHAR(50) NOT NULL COMMENT 'sku名称(冗余spu_name)',
  `price` DECIMAL(9,2) NOT NULL COMMENT '售价',
  `stock` INT(11) NOT NULL COMMENT '库存',
  `shop_id` BIGINT(20) NOT NULL COMMENT '商铺id,为0表示自营',
  `spu_id` BIGINT(20) NOT NULL COMMENT 'spu_id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='sku表';

/* sku增值保障 */
DROP TABLE IF EXISTS `goods_sku_safeguard`;
CREATE TABLE `goods_sku_safeguard` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku_id',
  `safeguard_id` BIGINT(20) NOT NULL COMMENT 'safeguard_id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='sku增值保障';

/* sku规格值 */
DROP TABLE IF EXISTS `goods_sku_spec_value`;
CREATE TABLE `goods_sku_spec_value` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku_id',
  `spec_value_id` BIGINT(20) NOT NULL COMMENT '规格值id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='sku规格值';

/* 规格表 */
DROP TABLE IF EXISTS `goods_spec`;
CREATE TABLE `goods_spec` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  /*`no` VARCHAR(50) NOT NULL COMMENT '规格编号',*/
  `name` VARCHAR(50) NOT NULL COMMENT '规格名称',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='规格表';

/* 规格值表 */
DROP TABLE IF EXISTS `goods_spec_value`;
CREATE TABLE `goods_spec_value` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `spec_id` BIGINT(20) NOT NULL COMMENT '规格id',
  `spec_value` VARCHAR(50) NOT NULL COMMENT '规格值',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='规格值表';

/* spu表 */
DROP TABLE IF EXISTS `goods_spu`;
CREATE TABLE `goods_spu` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(50) NOT NULL COMMENT '商品编号，唯一',
  `goods_name` VARCHAR(50) NOT NULL COMMENT '商品名称',
  `low_price` DECIMAL(9,2) NOT NULL COMMENT '最低售价',
  `category_id` BIGINT(20) NOT NULL COMMENT '分类id',
  `brand_id` BIGINT(20) NOT NULL COMMENT '品牌id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='spu表';

/* spu规格表 */
DROP TABLE IF EXISTS `goods_spu_spec`;
CREATE TABLE `goods_spu_spec` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `spu_id` BIGINT(20) NOT NULL COMMENT 'spu_id',
  `spec_id` BIGINT(20) NOT NULL COMMENT 'spec_id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='spu规格表';

-- 商品图片表
-- drop table if exists shop_album;create table shop_album(id INT UNSIGNED AUTO_INCREMENT key comment 'id',pid INT UNSIGNED not null comment '商品id',albumPath VARCHAR(50) not null comment '图片路径',goods_sthumb VARCHAR(255) comment '小缩略图片名称');

/* 店铺表 */
DROP TABLE IF EXISTS `shop_info`;
CREATE TABLE `shop_info` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT '店铺名称',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='店铺表';


########## 订单表 ##########

/* 购物车表 */
DROP TABLE IF EXISTS `order_cart`;
CREATE TABLE `order_cart` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku_id',
  `spu_id` BIGINT(20) NOT NULL COMMENT 'spu_id',
  `user_id` BIGINT(20) NOT NULL COMMENT 'user_id',
  `shop_id` BIGINT(20) NOT NULL COMMENT 'shop_id',
  `goods_name` VARCHAR(50) NOT NULL COMMENT '商品名称',
  `goods_num` INT(11) NOT NULL COMMENT '商品数量',
  `goods_price` DECIMAL(9,2) NOT NULL COMMENT '商品价格',
  `status` TINYINT(3) UNSIGNED NOT NULL COMMENT '状态（10: , 20: , 30: ...下单之后对应商品就不应该显示在购物车了）',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='购物车表';

/* 订单表 */
DROP TABLE IF EXISTS `order_info`;
CREATE TABLE `order_info` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `user_id` BIGINT(20) NOT NULL COMMENT 'user_id',
  `shop_id` BIGINT(20) NOT NULL COMMENT 'shop_id',
  `order_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '下单时间',
  `payment_way` TINYINT(3) NOT NULL COMMENT '支付方式（可用数字表示，如1：支付宝，2：微信，3：银行卡...）',
  `payment_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '支付时间',
  `total_amount` DECIMAL(9,2) NOT NULL COMMENT '商品总额',
  `carriage` DECIMAL(9,2) NOT NULL COMMENT '运费',
  `payment_amount` DECIMAL(9,2) NOT NULL COMMENT '实际付款',
  `status` TINYINT(3) UNSIGNED NOT NULL COMMENT '状态（10: , 20: , 30: ...）',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_no` (`no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表';

/* 订单商品表 */
DROP TABLE IF EXISTS `order_product`;
CREATE TABLE `order_product` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku_id',
  `spu_id` BIGINT(20) NOT NULL COMMENT 'spu_id',
  `shop_id` BIGINT(20) NOT NULL COMMENT 'shop_id',
  `goods_name` VARCHAR(50) NOT NULL COMMENT '商品名称',
  `goods_num` INT(11) NOT NULL COMMENT '商品数量',
  `goods_price` DECIMAL(9,2) NOT NULL COMMENT '商品价格',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单商品表';

/* 物流表 */
DROP TABLE IF EXISTS `order_logistics`;
CREATE TABLE `order_logistics` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `express_no` VARCHAR(50) NOT NULL COMMENT '快递单号',
  `logistics_comp_id` BIGINT(20) NOT NULL COMMENT '物流公司id',
  `delivery_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '发货时间',
  `receiving_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '收货时间',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='物流表';

/* 物流跟踪表 */
DROP TABLE IF EXISTS `order_logistics_flow`;
CREATE TABLE `order_logistics_flow` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `express_no` VARCHAR(50) NOT NULL COMMENT '快递单号',
  `info` VARCHAR(1000) NOT NULL COMMENT '跟踪信息',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='物流跟踪表';


/* 订单发票 */
/*DROP TABLE IF EXISTS `order_invoice`;
CREATE TABLE `order_invoice` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单发票';*/

/* 支付记录表 */
DROP TABLE IF EXISTS `order_pay_history`;
CREATE TABLE `order_pay_history` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `total_amount` DECIMAL(9,2) NOT NULL COMMENT '订单总额',
  `payment_amount` DECIMAL(9,2) NOT NULL COMMENT '支付金额',
  `payment_json` VARCHAR(1000) NOT NULL COMMENT '第三方支付平台参数信息',
  `remark` VARCHAR(100) NOT NULL COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='支付记录表';

/* 订单评论 */
DROP TABLE IF EXISTS `order_product_comment`;
CREATE TABLE `order_product_comment` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku_id` BIGINT(20) NOT NULL COMMENT 'sku_id',
  `spu_id` BIGINT(20) NOT NULL COMMENT 'spu_id',
  `user_id` BIGINT(20) NOT NULL COMMENT 'user_id',
  `user_nickname` VARCHAR(50) NOT NULL COMMENT '用户昵称',
  `like_num` INT(11) NOT NULL COMMENT '点赞数',
  `comment` VARCHAR(500) NOT NULL COMMENT '评论内容',
  `score` TINYINT(3) UNSIGNED NOT NULL COMMENT '评论分数（1~5分）',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单评论';


########## 用户表 ##########

/* 用户表 */
DROP TABLE IF EXISTS `user_info`;
CREATE TABLE `user_info` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名称必须唯一',
  `nickname` VARCHAR(50) NOT NULL COMMENT '用户昵称',
  `password` VARCHAR(50) NOT NULL COMMENT '用户密码',
  `mobile` VARCHAR(50) NOT NULL COMMENT '手机号',
  `email` VARCHAR(50) NOT NULL COMMENT '邮箱',
  `avatar` VARCHAR(100) NOT NULL COMMENT '头像url',
  `default_address_id` BIGINT(20) COMMENT '默认收货地址id',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';

/* 用户收货地址表 */
DROP TABLE IF EXISTS `user_address`;
CREATE TABLE `user_address` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL UNIQUE COMMENT '用户id',
  /*省、市、区*/
  `detailed_address` VARCHAR(50) NOT NULL COMMENT '详细地址',
  `contacts` VARCHAR(50) NOT NULL COMMENT '联系人',
  `mobile` VARCHAR(50) NOT NULL COMMENT '手机号',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';


########## 权限表 ##########
/* 角色表 */
DROP TABLE IF EXISTS `r_role`;
CREATE TABLE `r_role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL UNIQUE COMMENT '角色名称必须唯一',
  `remark` VARCHAR(100) NOT NULL COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
/* 权限表 */
DROP TABLE IF EXISTS `r_right`;
CREATE TABLE `r_right` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '父权限id',
  `name` VARCHAR(50) NOT NULL UNIQUE COMMENT '权限名称必须唯一',
  `remark` VARCHAR(100) NOT NULL COMMENT '备注',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
/* 角色权限表 */
DROP TABLE IF EXISTS `r_role_right`;
CREATE TABLE `r_role_right` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` BIGINT(20) NOT NULL,
  `right_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
/* 用户角色表 */
DROP TABLE IF EXISTS `r_user_role`;
CREATE TABLE `r_user_role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
